language: java
jdk:
  - openjdk8

branches:
  only:
    - development

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r tire-erp-server tire-erp-server
  - mkdir -p deploy
  - mv tire-erp-server.zip deploy/tire-erp-server.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-deploy-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: yglee8048/tire-erp-server
      branch: development

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - yglee8048@naver.com