language: java
jdk:
  - openjdk8

branches:
  only:
    - development

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - "chmod +x ./gradlew"
  - "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - yglee8048@naver.com