version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - sudo ./gradlew bootJar
  post_build:
    commands:
      - echo Build Completed.
artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes