spring:
  datasource:
    url: dev-erp-rds.cztekutconfc.ap-northeast-2.rds.amazonaws.com
    username: root
    password: minsooco
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace