server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 500
        format_sql: true
#        show_sql: true
    hibernate:
      ddl-auto: create

  datasource:
    platform: org.hibernate.dialect.MySQL5Dialect
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://tire-erp-dev-01.chjn91qrgnxy.ap-northeast-2.rds.amazonaws.com:3306/tiredb?autoReconnect=true
    username: root
    password: minsooco
    hikari:
      connection-timeout: 20000
      maximumPoolSize: 5