spring:
  datasource:
    url: jdbc:mariadb://dev-erp-rds.cztekutconfc.ap-northeast-2.rds.amazonaws.com/erp_db?autoReconnect=true
    username: root
    password: minsooco
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
#    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

logging.level:
  root: info
  org.hibernate.SQL: debug
  # org.hibernate.type: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 1000