spring:
  datasource:
    url: jdbc:mariadb://tire-db.cvwipzumkn8l.ap-northeast-2.rds.amazonaws.com:3306/erp_db?autoReconnect=true
    username: root
    password: tiredot22!
    driver-class-name: org.mariadb.jdbc.Driver

logging.level:
  root: info
  org.hibernate.SQL: debug
