server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mariadb://dev-erp-rds.cztekutconfc.ap-northeast-2.rds.amazonaws.com/erp_db?autoReconnect=true
    username: root
    password: minsooco
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret: Y29tLm1pbnNvby5jby50aXJlLWVycC1zZXJ2ZXIuc2VjcmV0LWtleS4yMDIxLTEyLTIwVDEwOjM0OjQxKzA5OjAw
  token-expired-in-milli-seconds: 1800000   # 30분

springdoc:
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true

logging.level:
  root: info
  org.hibernate.SQL: debug