server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 5000

spring:
  datasource:
    url: jdbc:mariadb://tire-db.cvwipzumkn8l.ap-northeast-2.rds.amazonaws.com:3306/erp_db?autoReconnect=true
#    url: jdbc:mariadb://localhost:3306/erp_db?autoReconnect=true
    username: root
    password: tiredot22!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        discriminator:
          ignore_explicit_for_joined: false
        format_sql: true
        default_batch_fetch_size: 500
        globally_quoted_identifiers: true
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret: Y29tLm1pbnNvby5jby50aXJlLWVycC1zZXJ2ZXIuc2VjcmV0LWtleS4yMDIxLTEyLTIwVDEwOjM0OjQxKzA5OjAw
  token-expired-in-milli-seconds: 3600000   # 60분

springdoc:
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true

logging.level:
  root: info
  org.hibernate.SQL: debug